export default {
    "code": 0,
    "msg": "success",
    "data": [
        {
            "id": 1000,
            "parentId": -1,
            "icon": "icon-quanxianguanli",
            "name": "组织管理",
            "spread": false,
            "path": "/upms4",
            "component": "Layout",
            "authority": null,
            "redirect": null,
            "keepAlive": "0",
            "code": null,
            "type": "0",
            "label": "组织管理",
            "sort": 0,
            "children": [
                {
                    "id": 1100,
                    "parentId": 1000,
                    "children": [],
                    "icon": "icon-yonghuguanli",
                    "name": "公司管理",
                    "spread": false,
                    "path": "user",
                    "component": "views/admin/user/index",
                    "authority": null,
                    "redirect": null,
                    "keepAlive": "1",
                    "code": null,
                    "type": "0",
                    "label": "公司管理",
                    "sort": 1
                },
                {
                    "id": 1200,
                    "parentId": 1000,
                    "children": [],
                    "icon": "icon-caidanguanli",
                    "name": "岗位管理",
                    "spread": false,
                    "path": "menu",
                    "component": "views/admin/menu/index",
                    "authority": null,
                    "redirect": null,
                    "keepAlive": "0",
                    "code": null,
                    "type": "0",
                    "label": "岗位管理",
                    "sort": 2
                },
                {
                    "id": 1300,
                    "parentId": 1000,
                    "children": [],
                    "icon": "icon-jiaoseguanli",
                    "name": "用户管理",
                    "spread": false,
                    "path": "role",
                    "component": "views/admin/role/index",
                    "authority": null,
                    "redirect": null,
                    "keepAlive": "0",
                    "code": null,
                    "type": "0",
                    "label": "用户管理",
                    "sort": 3
                }
            ]
        },
        {
            "id": 2000,
            "parentId": -1,
            "icon": "icon-quanxianguanli",
            "name": "权限管理",
            "spread": false,
            "path": "/upms1",
            "component": "Layout",
            "authority": null,
            "redirect": null,
            "keepAlive": "0",
            "code": null,
            "type": "0",
            "label": "权限管理",
            "sort": 0,
            "children": [
                {
                    "id": 2100,
                    "parentId": 2000,
                    "children": [],
                    "icon": "icon-yonghuguanli",
                    "name": "系统管理员",
                    "spread": false,
                    "path": "user",
                    "component": "views/admin/user/index",
                    "authority": null,
                    "redirect": null,
                    "keepAlive": "1",
                    "code": null,
                    "type": "0",
                    "label": "系统管理员",
                    "sort": 1
                },
                {
                    "id": 2200,
                    "parentId": 2000,
                    "children": [],
                    "icon": "icon-caidanguanli",
                    "name": "公司管理员",
                    "spread": false,
                    "path": "menu",
                    "component": "views/admin/menu/index",
                    "authority": null,
                    "redirect": null,
                    "keepAlive": "0",
                    "code": null,
                    "type": "0",
                    "label": "公司管理员",
                    "sort": 2
                },
                {
                    "id": 2300,
                    "parentId": 2000,
                    "children": [],
                    "icon": "icon-jiaoseguanli",
                    "name": "平台管理员",
                    "spread": false,
                    "path": "role",
                    "component": "views/admin/role/index",
                    "authority": null,
                    "redirect": null,
                    "keepAlive": "0",
                    "code": null,
                    "type": "0",
                    "label": "平台管理员",
                    "sort": 3
                },
                {
                    "id": 2400,
                    "parentId": 2000,
                    "children": [],
                    "icon": "icon-jiaoseguanli",
                    "name": "角色管理",
                    "spread": false,
                    "path": "role",
                    "component": "views/admin/role/index",
                    "authority": null,
                    "redirect": null,
                    "keepAlive": "0",
                    "code": null,
                    "type": "0",
                    "label": "角色管理",
                    "sort": 3
                },
                {
                    "id": 2500,
                    "parentId": 2000,
                    "children": [],
                    "icon": "icon-yonghuguanli",
                    "name": "菜单管理",
                    "spread": false,
                    "path": "user",
                    "component": "views/admin/user/index",
                    "authority": null,
                    "redirect": null,
                    "keepAlive": "1",
                    "code": null,
                    "type": "0",
                    "label": "菜单管理",
                    "sort": 1
                }
            ]
        },
        {
            "id": 3000,
            "parentId": -1,
            "icon": "icon-quanxianguanli",
            "name": "系统设置",
            "spread": false,
            "path": "/upms2",
            "component": "Layout",
            "authority": null,
            "redirect": null,
            "keepAlive": "0",
            "code": null,
            "type": "0",
            "label": "系统设置",
            "sort": 0,
            "children": [
                {
                    "id": 3200,
                    "parentId": 3000,
                    "children": [],
                    "icon": "icon-caidanguanli",
                    "name": "模块管理",
                    "spread": false,
                    "path": "menu",
                    "component": "views/admin/menu/index",
                    "authority": null,
                    "redirect": null,
                    "keepAlive": "0",
                    "code": null,
                    "type": "0",
                    "label": "模块管理",
                    "sort": 2
                },
                {
                    "id": 3300,
                    "parentId": 3000,
                    "children": [],
                    "icon": "icon-jiaoseguanli",
                    "name": "系统参数设置",
                    "spread": false,
                    "path": "role",
                    "component": "views/admin/role/index",
                    "authority": null,
                    "redirect": null,
                    "keepAlive": "0",
                    "code": null,
                    "type": "0",
                    "label": "系统参数设置",
                    "sort": 3
                },
                {
                    "id": 3400,
                    "parentId": 3000,
                    "children": [],
                    "icon": "icon-jiaoseguanli",
                    "name": "字典管理",
                    "spread": false,
                    "path": "role",
                    "component": "views/admin/role/index",
                    "authority": null,
                    "redirect": null,
                    "keepAlive": "0",
                    "code": null,
                    "type": "0",
                    "label": "字典管理",
                    "sort": 3
                }
            ]
        },
        {
            "id": 4000,
            "parentId": -1,
            "icon": "icon-quanxianguanli",
            "name": "系统监控",
            "spread": false,
            "path": "/upms3",
            "component": "Layout",
            "authority": null,
            "redirect": null,
            "keepAlive": "0",
            "code": null,
            "type": "0",
            "label": "系统监控",
            "sort": 0,
            "children": [
                {
                    "id": 4200,
                    "parentId": 4000,
                    "children": [],
                    "icon": "icon-caidanguanli",
                    "name": "在线用户",
                    "spread": false,
                    "path": "menu",
                    "component": "views/admin/menu/index",
                    "authority": null,
                    "redirect": null,
                    "keepAlive": "0",
                    "code": null,
                    "type": "0",
                    "label": "在线用户",
                    "sort": 2
                },
                {
                    "id": 4300,
                    "parentId": 4000,
                    "children": [],
                    "icon": "icon-jiaoseguanli",
                    "name": "访问日志",
                    "spread": false,
                    "path": "role",
                    "component": "views/admin/role/index",
                    "authority": null,
                    "redirect": null,
                    "keepAlive": "0",
                    "code": null,
                    "type": "0",
                    "label": "访问日志",
                    "sort": 3
                },
                {
                    "id": 4400,
                    "parentId": 4000,
                    "children": [],
                    "icon": "icon-jiaoseguanli",
                    "name": "作业监控",
                    "spread": false,
                    "path": "role",
                    "component": "views/admin/role/index",
                    "authority": null,
                    "redirect": null,
                    "keepAlive": "0",
                    "code": null,
                    "type": "0",
                    "label": "作业监控",
                    "sort": 3
                },
                {
                    "id": 4400,
                    "parentId": 4000,
                    "children": [],
                    "icon": "icon-jiaoseguanli",
                    "name": "数据监控",
                    "spread": false,
                    "path": "role",
                    "component": "views/admin/role/index",
                    "authority": null,
                    "redirect": null,
                    "keepAlive": "0",
                    "code": null,
                    "type": "0",
                    "label": "数据监控",
                    "sort": 3
                },
                {
                    "id": 4400,
                    "parentId": 4000,
                    "children": [],
                    "icon": "icon-jiaoseguanli",
                    "name": "缓存监控",
                    "spread": false,
                    "path": "role",
                    "component": "views/admin/role/index",
                    "authority": null,
                    "redirect": null,
                    "keepAlive": "0",
                    "code": null,
                    "type": "0",
                    "label": "缓存监控",
                    "sort": 3
                },
                {
                    "id": 4400,
                    "parentId": 4000,
                    "children": [],
                    "icon": "icon-jiaoseguanli",
                    "name": "注册中心",
                    "spread": false,
                    "path": "role",
                    "component": "views/admin/role/index",
                    "authority": null,
                    "redirect": null,
                    "keepAlive": "0",
                    "code": null,
                    "type": "0",
                    "label": "注册中心",
                    "sort": 3
                },
                {
                    "id": 4400,
                    "parentId": 4000,
                    "children": [],
                    "icon": "icon-jiaoseguanli",
                    "name": "springbootadmin",
                    "spread": false,
                    "path": "role",
                    "component": "views/admin/role/index",
                    "authority": null,
                    "redirect": null,
                    "keepAlive": "0",
                    "code": null,
                    "type": "0",
                    "label": "springbootadmin",
                    "sort": 3
                },
                {
                    "id": 4400,
                    "parentId": 4000,
                    "children": [],
                    "icon": "icon-jiaoseguanli",
                    "name": "链路监控",
                    "spread": false,
                    "path": "role",
                    "component": "views/admin/role/index",
                    "authority": null,
                    "redirect": null,
                    "keepAlive": "0",
                    "code": null,
                    "type": "0",
                    "label": "链路监控",
                    "sort": 3
                },
                {
                    "id": 4400,
                    "parentId": 4000,
                    "children": [],
                    "icon": "icon-jiaoseguanli",
                    "name": "服务降级监控",
                    "spread": false,
                    "path": "role",
                    "component": "views/admin/role/index",
                    "authority": null,
                    "redirect": null,
                    "keepAlive": "0",
                    "code": null,
                    "type": "0",
                    "label": "服务降级监控",
                    "sort": 3
                }
            ]
        },
        {
			"id": 5000,
			"parentId": -1,
			"children": [],
			"icon": "icon-weibiaoti46",
			"name": "代码生成器",
			"spread": false,
			"path": "/gen",
			"component": "views/gen/index",
			"authority": null,
			"redirect": null,
			"keepAlive": "0",
			"code": null,
			"type": "0",
			"label": "代码生成器",
			"sort": 8
		}
    ]
}